### ISSUE TITLE
OSError: [Errno 116] ETIMEDOUT

### ISSUE THREAD

**Issue by renatojobal** [vergoh/micropython-spotify-status-display#3]
Hi. Any one can help me? I am getting this error after uploading all files with Micropython and reloading:
```
MPY: soft reboot
no "memdebug" file or directory found, memory debug output disabled
Traceback (most recent call last):
  File "main.py", line 3, in <module>
  File "spotify.py", line 38, in __init__
  File "oled.py", line 15, in __init__
  File "ssd1306.py", line 124, in __init__
  File "ssd1306.py", line 40, in __init__
  File "ssd1306.py", line 65, in init_display
  File "ssd1306.py", line 129, in write_cmd
OSError: [Errno 116] ETIMEDOUT
MicroPython v1.21.0 on 2023-10-05; Generic ESP32 module with ESP32
Type "help()" for more information.
```
I reasearched about the issue but I am not getting a clear answer. Maybe someone had this problem too?

**Comment by vergoh** [comment]
Check how you've connected and configured the OLED display. Based on that traceback, the first command sent via i2c fails to result in a reply from the display.

**Comment by renatojobal** [comment]
I am using the [0.96" SSD1306](https://www.google.com/search?q=128x64+oled+i2c+0.96+ssd1306). I should have to do any configuration on the code or on the config.json file? Thank you for your response :D

**Comment by renatojobal** [comment]
Forget about it, I was using the SSD1315 :/

**Comment by renatojobal** [comment]
Thank you anyway :D

**Comment by vergoh** [comment]
Search results for SSD1315 are a little bit conflicting if it does work with the same interface as SSD1306 not. Could possibly still be worth a try. Which ESP32 board do you have? Doesn't hurt to a least check the wiring. https://github.com/vergoh/micropython-spotify-status-display/blob/master/Wiring.md (buttons are optional) is correct for "Lolin32 Lite" but for other boards the correct pins are likely to differ.

**Comment by renatojobal** [comment]
Yup, I will try, I would love to contribute If I find a solution.
Btw, I am using this 
<img width="259" alt="image" src="https://github.com/vergoh/micropython-spotify-status-display/assets/35740463/74fd4644-4162-472f-8813-a658e15cb249">
 
 But now I am facing another error that belongs to another issue.

**Comment by vergoh** [comment]
Haven't seen that board before but this appears to be the pinout:
![image](https://github.com/vergoh/micropython-spotify-status-display/assets/4665189/e61f4207-17dc-433e-958b-c55a67b848fe)
You'd want to use the pins columns marked with white background on the pcb. SCL is in GPIO 22, SDA is in GPIO 21 and GND can also be found from the right side. 3V3 can be found from the left side. Led is in GPIO 2.

With this information, the pins part of config.json would look like:
```
	"pins": {
		"led": 2,
		"scl": 22,
		"sda": 21,
		"button_playpause": 18,
		"button_next": 19,
		"buzzer": 23
	},
```
I've mapped here the optional buttons and buzzer to other free pins.
